# Generated by Django 5.2.2 on 2025-06-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_user_enrollment_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
