# Generated by Django 5.2.2 on 2025-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=100),
            preserve_default=False,
        ),
    ]
