# Generated by Django 5.2.3 on 2025-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images\\default-profile-icon.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
