# Generated by Django 5.2.2 on 2025-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_otp',
            field=models.IntegerField(default=654321),
        ),
    ]
