# Generated by Django 5.2.2 on 2025-06-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_user_forgot_password_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forgot_password_otp',
        ),
    ]
