# Generated by Django 5.2.2 on 2025-06-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_document_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='likes',
        ),
    ]
